DROP DATABASE IF EXISTS `CelestialAtlas`;
CREATE DATABASE `CelestialAtlas` CHARACTER SET utf8;

USE `CelestialAtlas`;

CREATE TABLE `Atlas`
(
  `id`          TINYINT         UNSIGNED    PRIMARY KEY AUTO_INCREMENT,
  `name`        VARCHAR(50)     NOT NULL,
  `wiki`        VARCHAR(20),
  `year`        VARCHAR(4)      NOT NULL,
  `author_name` VARCHAR(50)     NOT NULL,
  `author_wiki` VARCHAR(50)
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `Map`
(
  `id`          SMALLINT        UNSIGNED    PRIMARY KEY     AUTO_INCREMENT,
  `name`        VARCHAR(10)     NOT NULL,
  `description` VARCHAR(120)    NOT NULL,
  `atlas_id`    TINYINT         UNSIGNED    NOT NULL,
  CONSTRAINT    `fk_atlas_id`   FOREIGN KEY (`atlas_id`)    REFERENCES  `Atlas`(`id`)
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

INSERT INTO `Atlas`
(`name`,                                        `wiki`,                 `year`, `author_name`,                                      `author_wiki`)
VALUES
('Kitab Suwar al Kawakib',                      'Book_of_Fixed_Stars',  '964',  'Abd al-Rahman al-Sufi',                            'Abd_al-Rahman_al-Sufi'),
('Kitab Suwar al Kawakib',                      'Book_of_Fixed_Stars',  '1417', 'Abd al-Rahman al-Sufi',                            'Abd_al-Rahman_al-Sufi'),
('Souwar al-Kawakib al-Thabita',                'Zij-i_Sultani',        '1436', 'Zahir al-Din Ulugh Beg Kurakan',                   'Ulugh_Beg'),
('Uranometria',                                 'Uranometria',          '1603', 'Johann Bayer',                                     'Johann_Bayer'),
('Uranographia',                                '',                     '1690', 'Johannes Hevelius',                                'Johannes_Hevelius'),
('Globi Coelestis',                             '',                     '1693', 'Ignace-Gaston Pardies',                            'Ignace-Gaston_Pardies'),
('Mercurii Philisophici Firmamentum Firmianum', '',                     '1730', 'Thomas Corbinianus',                               ''),
('Atlas Coelestis',                             'Atlas_Coelestis',      '1753', 'John Flamsteed',                                   'John_Flamsteed'),
('Atlas Céleste',                               '',                     '1776', 'Jean Nicolas Fortin',                              'Jean_Nicolas_Fortin'),
('Vorstellung der Gestirne auf XXXIV Tafeln',   '',                     '1805', 'Johann Elert Bode',                                'Johann_Elert_Bode'),
('A Celestial Atlas',                           'A_Celestial_Atlas',    '1822', 'Alexander Jamieson',                               'Alexander_Jamieson'),
('Astronomical Recreations',                    '',                     '1824', 'Jacob Green',                                      ''),
('Urania Mirror',                               'Urania''s_Mirror',     '1824', 'Richard Rouse Bloxam',                             ''),
('The Geography of the Heavens',                '',                     '1835', 'Elijah Hinsdale Burritt',                          ''),
('The Stars',                                   '',                     '1844', 'William Rutter Dawes',                             'William_Rutter_Dawes'),
('Smith Illustrated Astronomy',                 '',                     '1850', 'Asa Smith',                                        ''),
('Astronomischen Bilderatlas',                  '',                     '1855', 'Ludwig Preyssinger',                               ''),
('The Stars',                                   '',                     '1865', 'Society for the Diffusion of Useful Knowledge',    'Society_for_the_Diffusion_of_Useful_Knowledge'),
('Atlas of Astronomy',                          '',                     '1869', 'Alexander Keith Johnston',                         'Alexander_Keith_Johnston_(1844–1879)');

INSERT INTO `Map`
(`name`,        `description`,                                                                                                              `atlas_id`)
VALUES
('964as01',     'Ursa Minor',                                                                                                               '1'),
('964as02',     'Ursa Major',                                                                                                               '1'),
('964as03',     'Draco',                                                                                                                    '1'),
('964as04',     'Cepheus',                                                                                                                  '1'),
('964as05',     'Bootes',                                                                                                                   '1'),
('964as06',     'Corona Borealis',                                                                                                          '1'),
('964as07',     'Hercules',                                                                                                                 '1'),
('964as08',     'Lyra',                                                                                                                     '1'),
('964as09',     'Cygnus',                                                                                                                   '1'),
('964as10',     'Cassiopeia',                                                                                                               '1'),
('964as11',     'Perseus',                                                                                                                  '1'),
('964as12',     'Auriga',                                                                                                                   '1'),
('964as13',     'Ophiuchus & Serpens',                                                                                                      '1'),
('964as14',     'Sagitta',                                                                                                                  '1'),
('964as15',     'Aquila',                                                                                                                   '1'),
('964as16',     'Delphinus',                                                                                                                '1'),
('964as17',     'Equuleus',                                                                                                                 '1'),
('964as18',     'Pegasus',                                                                                                                  '1'),
('964as19',     'Andromeda',                                                                                                                '1'),
('964as20',     'Triangulum',                                                                                                               '1'),
('964as21',     'Aries',                                                                                                                    '1'),
('964as22',     'Taurus',                                                                                                                   '1'),
('964as23',     'Gemini',                                                                                                                   '1'),
('964as24',     'Cancer',                                                                                                                   '1'),
('964as25',     'Leo',                                                                                                                      '1'),
('964as26',     'Virgo',                                                                                                                    '1'),
('964as27',     'Libra',                                                                                                                    '1'),
('964as28',     'Scorpius',                                                                                                                 '1'),
('964as29',     'Sagittarius',                                                                                                              '1'),
('964as30',     'Capricornus',                                                                                                              '1'),
('964as31',     'Aquarius',                                                                                                                 '1'),
('964as32',     'Pisces',                                                                                                                   '1'),
('964as33',     'Cetus',                                                                                                                    '1'),
('964as34',     'Orion',                                                                                                                    '1'),
('964as35',     'Eridanus',                                                                                                                 '1'),
('964as36',     'Lepus',                                                                                                                    '1'),
('964as37',     'Canis Major',                                                                                                              '1'),
('964as38',     'Canis Minor',                                                                                                              '1'),
('964as39',     'Argo Navis',                                                                                                               '1'),
('964as40',     'Hydra',                                                                                                                    '1'),
('964as41',     'Crater',                                                                                                                   '1'),
('964as42',     'Corvus',                                                                                                                   '1'),
('964as43',     'Centaurus & Lupus',                                                                                                        '1'),
('964as44',     'Ara',                                                                                                                      '1'),
('964as45',     'Corona Australis',                                                                                                         '1'),
('964as46',     'Piscis Austrinus',                                                                                                         '1'),
('1417as01',    'Ursa Minor (sphere)',                                                                                                      '2'),
('1417as02',    'Ursa Minor (roof)',                                                                                                       '2'),
('1417as03',    'Ursa Major (sphere)',                                                                                                      '2'),
('1417as04',    'Ursa Major (roof)',                                                                                                       '2'),
('1417as05',    'Draco (sphere)',                                                                                                           '2'),
('1417as06',    'Draco (roof)',                                                                                                            '2'),
('1417as07',    'Cepheus (sphere)',                                                                                                         '2'),
('1417as08',    'Cepheus (roof)',                                                                                                          '2'),
('1417as09',    'Bootes (sphere)',                                                                                                          '2'),
('1417as10',    'Bootes (roof)',                                                                                                           '2'),
('1417as11',    'Corona Borealis',                                                                                                          '2'),
('1417as12',    'Hercules (sphere)',                                                                                                        '2'),
('1417as13',    'Hercules (roof)',                                                                                                         '2'),
('1417as14',    'Lyra (sphere)',                                                                                                            '2'),
('1417as15',    'Lyra (roof)',                                                                                                             '2'),
('1417as16',    'Cygnus (sphere)',                                                                                                          '2'),
('1417as17',    'Cygnus (roof)',                                                                                                           '2'),
('1417as18',    'Cassiopeia (sphere)',                                                                                                      '2'),
('1417as19',    'Cassiopeia (roof)',                                                                                                       '2'),
('1417as20',    'Perseus (sphere)',                                                                                                         '2'),
('1417as21',    'Perseus (roof)',                                                                                                          '2'),
('1417as22',    'Auriga (sphere)',                                                                                                          '2'),
('1417as23',    'Auriga (roof)',                                                                                                           '2'),
('1417as24',    'Ophiuchus & Serpens (sphere)',                                                                                             '2'),
('1417as25',    'Ophiuchus & Serpens (roof)',                                                                                              '2'),
('1417as26',    'Sagitta',                                                                                                                  '2'),
('1417as27',    'Aquila (sphere)',                                                                                                          '2'),
('1417as28',    'Aquila (roof)',                                                                                                           '2'),
('1417as29',    'Delphinus (sphere)',                                                                                                       '2'),
('1417as30',    'Delphinus (roof)',                                                                                                        '2'),
('1417as31',    'Equuleus',                                                                                                                 '2'),
('1417as32',    'Pegasus (sphere)',                                                                                                         '2'),
('1417as33',    'Pegasus (roof)',                                                                                                          '2'),
('1417as34',    'Andromeda (sphere)',                                                                                                       '2'),
('1417as35',    'Andromeda (roof)',                                                                                                        '2'),
('1417as36',    'Triangulum',                                                                                                               '2'),
('1417as37',    'Aries (sphere)',                                                                                                           '2'),
('1417as38',    'Aries (roof)',                                                                                                            '2'),
('1417as39',    'Taurus (sphere)',                                                                                                          '2'),
('1417as40',    'Taurus (roof)',                                                                                                           '2'),
('1417as40',    'Gemini (sphere)',                                                                                                          '2'),
('1417as42',    'Gemini (roof)',                                                                                                           '2'),
('1417as43',    'Cancer (sphere)',                                                                                                          '2'),
('1417as44',    'Cancer (roof)',                                                                                                           '2'),
('1417as45',    'Leo (sphere)',                                                                                                             '2'),
('1417as46',    'Leo (roof)',                                                                                                              '2'),
('1417as47',    'Virgo (sphere)',                                                                                                           '2'),
('1417as48',    'Virgo (roof)',                                                                                                            '2'),
('1417as49',    'Libra (sphere)',                                                                                                           '2'),
('1417as50',    'Libra (roof)',                                                                                                            '2'),
('1417as51',    'Scorpius (sphere)',                                                                                                        '2'),
('1417as52',    'Scorpius (roof)',                                                                                                         '2'),
('1417as53',    'Sagittarius (sphere)',                                                                                                     '2'),
('1417as54',    'Sagittarius (roof)',                                                                                                      '2'),
('1417as55',    'Capricornus (sphere)',                                                                                                     '2'),
('1417as56',    'Capricornus (roof)',                                                                                                      '2'),
('1417as57',    'Aquarius (sphere)',                                                                                                        '2'),
('1417as58',    'Aquarius (roof)',                                                                                                         '2'),
('1417as59',    'Pisces (sphere)',                                                                                                          '2'),
('1417as60',    'Pisces (roof)',                                                                                                           '2'),
('1417as61',    'Cetus (sphere)',                                                                                                           '2'),
('1417as62',    'Cetus (roof)',                                                                                                            '2'),
('1417as63',    'Orion (sphere)',                                                                                                           '2'),
('1417as64',    'Orion (roof)',                                                                                                            '2'),
('1417as65',    'Eridanus (sphere)',                                                                                                        '2'),
('1417as66',    'Eridanus (roof)',                                                                                                         '2'),
('1417as67',    'Lepus',                                                                                                                    '2'),
('1417as68',    'Canis Major (sphere)',                                                                                                     '2'),
('1417as69',    'Canis Major (roof)',                                                                                                      '2'),
('1417as70',    'Canis Minor (sphere)',                                                                                                     '2'),
('1417as71',    'Canis Minor (roof)',                                                                                                      '2'),
('1417as72',    'Argo Navis (sphere)',                                                                                                      '2'),
('1417as73',    'Argo Navis (roof)',                                                                                                       '2'),
('1417as74',    'Hydra (sphere)',                                                                                                           '2'),
('1417as75',    'Hydra (roof)',                                                                                                            '2'),
('1417as76',    'Crater',                                                                                                                   '2'),
('1417as77',    'Corvus (sphere)',                                                                                                          '2'),
('1417as78',    'Corvus (roof)',                                                                                                           '2'),
('1417as79',    'Centaurus & Lupus (sphere)',                                                                                               '2'),
('1417as80',    'Centaurus & Lupus (roof)',                                                                                                '2'),
('1417as81',    'Ara (sphere)',                                                                                                             '2'),
('1417as82',    'Ara (roof)',                                                                                                              '2'),
('1417as83',    'Corona Australis (sphere)',                                                                                                '2'),
('1417as84',    'Corona Australis (roof)',                                                                                                 '2'),
('1417as85',    'Piscis Austrinus',                                                                                                         '2'),
('1436ub01',    'Ursa Minor',                                                                                                               '3'),
('1436ub02',    'Ursa Major (sphere)',                                                                                                      '3'),
('1436ub03',    'Ursa Major (roof)',                                                                                                       '3'),
('1436ub04',    'Draco (sphere)',                                                                                                           '3'),
('1436ub05',    'Draco (roof)',                                                                                                            '3'),
('1436ub06',    'Cepheus (sphere)',                                                                                                         '3'),
('1436ub07',    'Cepheus (roof)',                                                                                                          '3'),
('1436ub08',    'Bootes (sphere)',                                                                                                          '3'),
('1436ub09',    'Bootes (roof)',                                                                                                           '3'),
('1436ub10',    'Corona Borealis',                                                                                                          '3'),
('1436ub11',    'Hercules (sphere)',                                                                                                        '3'),
('1436ub12',    'Hercules (roof)',                                                                                                         '3'),
('1436ub13',    'Lyra',                                                                                                                     '3'),
('1436ub14',    'Cygnus (sphere)',                                                                                                          '3'),
('1436ub15',    'Cygnus (roof)',                                                                                                           '3'),
('1436ub16',    'Cassiopeia (sphere)',                                                                                                      '3'),
('1436ub17',    'Cassiopeia (roof)',                                                                                                       '3'),
('1436ub18',    'Perseus (sphere)',                                                                                                         '3'),
('1436ub19',    'Perseus (roof)',                                                                                                          '3'),
('1436ub20',    'Auriga (sphere)',                                                                                                          '3'),
('1436ub21',    'Auriga (roof)',                                                                                                           '3'),
('1436ub22',    'Ophiuchus & Serpens (sphere)',                                                                                             '3'),
('1436ub23',    'Ophiuchus & Serpens (roof)',                                                                                              '3'),
('1436ub24',    'Sagitta',                                                                                                                  '3'),
('1436ub25',    'Aquila (sphere)',                                                                                                          '3'),
('1436ub26',    'Aquila (roof)',                                                                                                           '3'),
('1436ub27',    'Delphinus',                                                                                                                '3'),
('1436ub28',    'Equuleus',                                                                                                                 '3'),
('1436ub29',    'Pegasus (sphere)',                                                                                                         '3'),
('1436ub30',    'Pegasus (roof)',                                                                                                          '3'),
('1436ub31',    'Andromeda (sphere)',                                                                                                       '3'),
('1436ub32',    'Andromeda (roof)',                                                                                                        '3'),
('1436ub33',    'Triangulum',                                                                                                               '3'),
('1436ub34',    'Aries',                                                                                                                    '3'),
('1436ub35',    'Taurus (sphere)',                                                                                                          '3'),
('1436ub36',    'Taurus (roof)',                                                                                                           '3'),
('1436ub37',    'Gemini (sphere)',                                                                                                          '3'),
('1436ub38',    'Gemini (roof)',                                                                                                           '3'),
('1436ub39',    'Cancer',                                                                                                                   '3'),
('1436ub40',    'Leo (sphere)',                                                                                                             '3'),
('1436ub41',    'Leo (roof)',                                                                                                              '3'),
('1436ub42',    'Virgo (sphere)',                                                                                                           '3'),
('1436ub43',    'Virgo (roof)',                                                                                                            '3'),
('1436ub44',    'Libra',                                                                                                                    '3'),
('1436ub45',    'Scorpius (sphere)',                                                                                                        '3'),
('1436ub46',    'Scorpius (roof)',                                                                                                         '3'),
('1436ub47',    'Sagittarius (sphere)',                                                                                                     '3'),
('1436ub48',    'Sagittarius (roof)',                                                                                                      '3'),
('1436ub49',    'Capricornus',                                                                                                              '3'),
('1436ub50',    'Aquarius (sphere)',                                                                                                        '3'),
('1436ub51',    'Aquarius (roof)',                                                                                                         '3'),
('1436ub52',    'Pisces (sphere)',                                                                                                          '3'),
('1436ub53',    'Pisces (roof)',                                                                                                           '3'),
('1436ub54',    'Cetus (sphere)',                                                                                                           '3'),
('1436ub55',    'Cetus (roof)',                                                                                                            '3'),
('1436ub56',    'Orion (sphere)',                                                                                                           '3'),
('1436ub57',    'Orion (roof)',                                                                                                            '3'),
('1436ub58',    'Eridanus (sphere)',                                                                                                        '3'),
('1436ub59',    'Eridanus (roof)',                                                                                                         '3'),
('1436ub60',    'Lepus',                                                                                                                    '3'),
('1436ub61',    'Canis Major',                                                                                                              '3'),
('1436ub62',    'Canis Minor',                                                                                                              '3'),
('1436ub63',    'Argo Navis (sphere)',                                                                                                      '3'),
('1436ub64',    'Argo Navis (roof)',                                                                                                       '3'),
('1436ub65',    'Hydra (sphere)',                                                                                                           '3'),
('1436ub66',    'Hydra (roof)',                                                                                                            '3'),
('1436ub67',    'Crater',                                                                                                                   '3'),
('1436ub68',    'Corvus',                                                                                                                   '3'),
('1436ub69',    'Centaurus & Lupus (sphere)',                                                                                               '3'),
('1436ub70',    'Centaurus & Lupus (roof)',                                                                                                '3'),
('1436ub71',    'Ara',                                                                                                                      '3'),
('1436ub72',    'Corona Australis',                                                                                                         '3'),
('1436ub73',    'Piscis Austrinus',                                                                                                         '3'),
('1603jb01',    'Ursa Minor',                                                                                                               '4'),
('1603jb02',    'Ursa Major',                                                                                                               '4'),
('1603jb03',    'Draco',                                                                                                                    '4'),
('1603jb04',    'Cepheus',                                                                                                                  '4'),
('1603jb05',    'Bootes',                                                                                                                   '4'),
('1603jb06',    'Corona Borealis',                                                                                                          '4'),
('1603jb07',    'Hercules',                                                                                                                 '4'),
('1603jb08',    'Lyra',                                                                                                                     '4'),
('1603jb09',    'Cygnus',                                                                                                                   '4'),
('1603jb10',    'Cassiopeia',                                                                                                               '4'),
('1603jb11',    'Perseus',                                                                                                                  '4'),
('1603jb12',    'Auriga',                                                                                                                   '4'),
('1603jb13',    'Ophiuchus',                                                                                                                '4'),
('1603jb14',    'Serpens',                                                                                                                  '4'),
('1603jb15',    'Sagitta',                                                                                                                  '4'),
('1603jb16',    'Aquila',                                                                                                                   '4'),
('1603jb17',    'Delphinus',                                                                                                                '4'),
('1603jb18',    'Equuleus',                                                                                                                 '4'),
('1603jb19',    'Pegasus',                                                                                                                  '4'),
('1603jb20',    'Andromeda',                                                                                                                '4'),
('1603jb21',    'Triangulum',                                                                                                               '4'),
('1603jb22',    'Aries',                                                                                                                    '4'),
('1603jb23',    'Taurus',                                                                                                                   '4'),
('1603jb24',    'Gemini',                                                                                                                   '4'),
('1603jb25',    'Cancer',                                                                                                                   '4'),
('1603jb26',    'Leo',                                                                                                                      '4'),
('1603jb27',    'Virgo',                                                                                                                    '4'),
('1603jb28',    'Libra',                                                                                                                    '4'),
('1603jb29',    'Scorpius',                                                                                                                 '4'),
('1603jb30',    'Sagittarius',                                                                                                              '4'),
('1603jb31',    'Capricornus',                                                                                                              '4'),
('1603jb32',    'Aquarius',                                                                                                                 '4'),
('1603jb33',    'Pisces',                                                                                                                   '4'),
('1603jb34',    'Cetus',                                                                                                                    '4'),
('1603jb35',    'Orion',                                                                                                                    '4'),
('1603jb36',    'Eridanus',                                                                                                                 '4'),
('1603jb37',    'Lepus',                                                                                                                    '4'),
('1603jb38',    'Canis Major',                                                                                                              '4'),
('1603jb39',    'Canis Minor',                                                                                                              '4'),
('1603jb40',    'Argo Navis',                                                                                                               '4'),
('1603jb41',    'Centaurus',                                                                                                                '4'),
('1603jb42',    'Crater',                                                                                                                   '4'),
('1603jb43',    'Corvus',                                                                                                                   '4'),
('1603jb44',    'Hydra',                                                                                                                    '4'),
('1603jb45',    'Lupus',                                                                                                                    '4'),
('1603jb46',    'Ara',                                                                                                                      '4'),
('1603jb47',    'Corona Australis',                                                                                                         '4'),
('1603jb48',    'Piscis Austrinus',                                                                                                         '4'),
('1603jb49',    'Pavo',                                                                                                                     '4'),
('1603jb50',    'Emispherium Pars Prima',                                                                                                   '4'),
('1603jb51',    'Emispherium Pars Secunda',                                                                                                 '4'),
('1690jh01',    'Firmamentum Sobiescianum',                                                                                                 '5'),
('1690jh02',    'Hemisphaerium Boreale',                                                                                                    '5'),
('1690jh03',    'Hemisphaerium Australe',                                                                                                   '5'),
('1690jh04',    'Ursa Minor',                                                                                                               '5'),
('1690jh05',    'Draco',                                                                                                                    '5'),
('1690jh06',    'Cepheus',                                                                                                                  '5'),
('1690jh07',    'Ursa Major',                                                                                                               '5'),
('1690jh08',    'Canes Venatici',                                                                                                           '5'),
('1690jh09',    'Bootes, Coma Berenices & Mons Maenalus',                                                                                   '5'),
('1690jh10',    'Corona',                                                                                                                   '5'),
('1690jh11',    'Hercules & Cerberus',                                                                                                      '5'),
('1690jh12',    'Lyra',                                                                                                                     '5'),
('1690jh13',    'Cygnus',                                                                                                                   '5'),
('1690jh14',    'Vulpecula & Anser',                                                                                                        '5'),
('1690jh15',    'Lacerta sive Stellio',                                                                                                     '5'),
('1690jh16',    'Cassiopeia',                                                                                                               '5'),
('1690jh17',    'Camelopardalus',                                                                                                           '5'),
('1690jh18',    'Serpentarius & Serpens',                                                                                                   '5'),
('1690jh19',    'Scutum Sobiescian',                                                                                                        '5'),
('1690jh20',    'Aquila & Antinous',                                                                                                        '5'),
('1690jh21',    'Sagitta, Delphinus & Equuleus',                                                                                            '5'),
('1690jh22',    'Pegasus',                                                                                                                  '5'),
('1690jh23',    'Andromeda',                                                                                                                '5'),
('1690jh24',    'Perseus',                                                                                                                  '5'),
('1690jh25',    'Auriga',                                                                                                                   '5'),
('1690jh26',    'Lynx',                                                                                                                     '5'),
('1690jh27',    'Leo Minor',                                                                                                                '5'),
('1690jh28',    'Triangulum Majus, Minus & Musca',                                                                                          '5'),
('1690jh29',    'Aries',                                                                                                                    '5'),
('1690jh30',    'Taurus',                                                                                                                   '5'),
('1690jh31',    'Gemini',                                                                                                                   '5'),
('1690jh32',    'Cancer',                                                                                                                   '5'),
('1690jh33',    'Leo',                                                                                                                      '5'),
('1690jh34',    'Virgo',                                                                                                                    '5'),
('1690jh35',    'Libra',                                                                                                                    '5'),
('1690jh36',    'Scorpius',                                                                                                                 '5'),
('1690jh37',    'Sagittarius',                                                                                                              '5'),
('1690jh38',    'Capricornus',                                                                                                              '5'),
('1690jh39',    'Aquarius',                                                                                                                 '5'),
('1690jh40',    'Pisces',                                                                                                                   '5'),
('1690jh41',    'Cetus',                                                                                                                    '5'),
('1690jh42',    'Eridanus, Phoenix & Toucan',                                                                                               '5'),
('1690jh43',    'Orion',                                                                                                                    '5'),
('1690jh44',    'Monoceros',                                                                                                                '5'),
('1690jh45',    'Canis Minor',                                                                                                              '5'),
('1690jh46',    'Hydra & Robur Carolinum',                                                                                                  '5'),
('1690jh47',    'Sextans Uraniae',                                                                                                          '5'),
('1690jh48',    'Crater & Corvus',                                                                                                          '5'),
('1690jh49',    'Centaurus & Crux',                                                                                                         '5'),
('1690jh50',    'Lupus',                                                                                                                    '5'),
('1690jh51',    'Ara, Triangulum Australe & Pavo',                                                                                          '5'),
('1690jh52',    'Corona Australis',                                                                                                         '5'),
('1690jh53',    'Piscis Notius & Grus',                                                                                                     '5'),
('1690jh54',    'Lepus & Columba',                                                                                                          '5'),
('1690jh55',    'Canis Major',                                                                                                              '5'),
('1690jh56',    'Argo Navis',                                                                                                               '5'),
('1690jh57',    'Polus Antarcticus',                                                                                                        '5'),
('1693igp1',    'Ursa Major, Ursa Minor, Perseus & Constellations',                                                                         '6'),
('1693igp2',    'Cetus, Aquarius, Andromeda & Constellations',                                                                              '6'),
('1693igp3',    'Gemini, Orion, Taurus & Constellations',                                                                                   '6'),
('1693igp4',    'Virgo, Hydra & Constellations',                                                                                            '6'),
('1693igp5',    'Hercules, Sagittarius & Constellations',                                                                                   '6'),
('1693igp6',    'Centaurus, Indus, Chamaeleon & Constellations',                                                                            '6'),
('1730tc01',    'Cap I Fig 1 : Sphaera Armillaris',                                                                                         '7'),
('1730tc01',    'Cap I Fig 2 : Globus Coelestis',                                                                                           '7'),
('1730tc02',    'Cap I Fig 3 : Haemisphaerium CoeliBoreale',                                                                                '7'),
('1730tc03',    'Cap I Fig 4 : Haemisphaerium CoeliAustrale',                                                                               '7'),
('1730tc04',    'Cap I Fig 5',                                                                                                              '7'),
('1730tc05',    'Cap I Fig 6',                                                                                                              '7'),
('1730tc06',    'Cap I Fig 7',                                                                                                              '7'),
('1730tc07',    'Cap II Fig 1',                                                                                                             '7'),
('1730tc08',    'Cap II Fig 2',                                                                                                             '7'),
('1730tc09',    'Cap II Fig 3 : Rosa Nautica',                                                                                              '7'),
('1730tc10',    'Cap II Fig 4',                                                                                                             '7'),
('1730tc12',    'Cap II Fig 5',                                                                                                             '7'),
('1730tc13',    'Cap II Fig 6',                                                                                                             '7'),
('1730tc14',    'Cap II Fig 7',                                                                                                             '7'),
('1730tc15',    'Cap II Fig 8 : Orion',                                                                                                     '7'),
('1730tc16',    'Cap II Fig 9',                                                                                                             '7'),
('1730tc17',    'Cap II Fig 10 : Horologium Horizontale',                                                                                   '7'),
('1730tc18',    'Cap II Fig 11 : Astrodicticum',                                                                                            '7'),
('1730tc19',    'Cap II Fig 12 : Coelestium Mansionum Dispositio Astrologica',                                                              '7'),
('1730tc20',    'Cap II Fig 13, 14, 15 : Systema Genethliacum',                                                                             '7'),
('1730tc21',    'Cap III Fig 1 : Coelum Aegyptiacum - Hemisphaerium Boreale',                                                               '7'),
('1730tc22',    'Cap III Fig 2 : Coelum Aegyptiacum - Hemisphaerium Australe',                                                              '7'),
('1730tc23',    'Cap III Fig 3 : Systema Mundi Aegyptiacum',                                                                                '7'),
('1730tc24',    'Cap III Fig 4, 5, 6 : Systema Ptolemaicum, Tychonis, Riccioli',                                                            '7'),
('1730tc25',    'Cap III Fig 7 : Systema Copernicanum',                                                                                     '7'),
('1730tc26',    'Cap III Fig 8 : Systema Solis',                                                                                            '7'),
('1730tc27',    'Cap III Fig 9, 10, 11, 12, 13 : Saturnus, Jupiter, Mars, Mercurius, Venus',                                                '7'),
('1730tc28',    'Cap III Fig 14 : Tabula Selenographica',                                                                                   '7'),
('1730tc29',    'Cap III Fig 15 : Tabula Selenographica',                                                                                   '7'),
('1730tc30',    'Cap III Fig 16 : Ephemeris Lunaris',                                                                                       '7'),
('1730tc31',    'Ursa Minor',                                                                                                               '7'),
('1730tc32',    'Ursa Major & Ior-Dan',                                                                                                     '7'),
('1730tc33',    'Draco',                                                                                                                    '7'),
('1730tc34',    'Cepheus',                                                                                                                  '7'),
('1730tc35',    'Andromeda',                                                                                                                '7'),
('1730tc36',    'Cassiopeia',                                                                                                               '7'),
('1730tc37',    'Perseus & Caput Medusae',                                                                                                  '7'),
('1730tc38',    'Camelopardalis',                                                                                                           '7'),
('1730tc39',    'Bootes',                                                                                                                   '7'),
('1730tc40',    'Corona Firmiana Septentrionalis',                                                                                          '7'),
('1730tc41',    'Hercules',                                                                                                                 '7'),
('1730tc42',    'Lyra',                                                                                                                     '7'),
('1730tc43',    'Tigris Fluvius',                                                                                                           '7'),
('1730tc44',    'Cygnus',                                                                                                                   '7'),
('1730tc45',    'Sceptrum Imperiale',                                                                                                       '7'),
('1730tc46',    'Auriga',                                                                                                                   '7'),
('1730tc47',    'Serpentarius, Serpens & Scutum Sobiesci',                                                                                  '7'),
('1730tc48',    'Aquila & Sagitta',                                                                                                         '7'),
('1730tc49',    'Antinous',                                                                                                                 '7'),
('1730tc50',    'Delphinus',                                                                                                                '7'),
('1730tc51',    'Pegasus & Equuleus',                                                                                                       '7'),
('1730tc52',    'Triangulum & Lilium',                                                                                                      '7'),
('1730tc53',    'Coma Berenices',                                                                                                           '7'),
('1730tc54',    'Aries',                                                                                                                    '7'),
('1730tc55',    'Taurus',                                                                                                                   '7'),
('1730tc56',    'Gemini',                                                                                                                   '7'),
('1730tc57',    'Cancer',                                                                                                                   '7'),
('1730tc58',    'Leo',                                                                                                                      '7'),
('1730tc59',    'Virgo',                                                                                                                    '7'),
('1730tc60',    'Libra',                                                                                                                    '7'),
('1730tc61',    'Scorpius',                                                                                                                 '7'),
('1730tc62',    'Sagittarius',                                                                                                              '7'),
('1730tc63',    'Capricornus',                                                                                                              '7'),
('1730tc64',    'Aquarius',                                                                                                                 '7'),
('1730tc65',    'Pisces',                                                                                                                   '7'),
('1730tc66',    'Orion',                                                                                                                    '7'),
('1730tc67',    'Cetus',                                                                                                                    '7'),
('1730tc68',    'Eridanus',                                                                                                                 '7'),
('1730tc69',    'Lepus',                                                                                                                    '7'),
('1730tc70',    'Canis Major',                                                                                                              '7'),
('1730tc71',    'Canis Minor',                                                                                                              '7'),
('1730tc72',    'Columba',                                                                                                                  '7'),
('1730tc73',    'Monoceros',                                                                                                                '7'),
('1730tc74',    'Hydra, Sextans, Crater & Corvus',                                                                                          '7'),
('1730tc75',    'Centaurus & Lupus',                                                                                                        '7'),
('1730tc76',    'Ara',                                                                                                                      '7'),
('1730tc77',    'Piscis Notius',                                                                                                            '7'),
('1730tc78',    'Argo Navis & Robur Carolinum',                                                                                             '7'),
('1730tc79',    'Corona Australis',                                                                                                         '7'),
('1730tc80',    'Grus',                                                                                                                     '7'),
('1730tc81',    'Phoenix',                                                                                                                  '7'),
('1730tc82',    'Indus & Pavo',                                                                                                             '7'),
('1730tc83',    'Dorado',                                                                                                                   '7'),
('1730tc84',    'Polus Antarcticus',                                                                                                        '7'),
('1753jf01',    'Aries',                                                                                                                    '8'),
('1753jf02',    'Taurus',                                                                                                                   '8'),
('1753jf03',    'Gemini',                                                                                                                   '8'),
('1753jf04',    'Cancer',                                                                                                                   '8'),
('1753jf05',    'Leo',                                                                                                                      '8'),
('1753jf06',    'Virgo',                                                                                                                    '8'),
('1753jf07',    'Libra',                                                                                                                    '8'),
('1753jf08',    'Sagittarius',                                                                                                              '8'),
('1753jf09',    'Aquarius',                                                                                                                 '8'),
('1753jf10',    'Pisces',                                                                                                                   '8'),
('1753jf11',    'Cetus',                                                                                                                    '8'),
('1753jf12',    'Eridanus, Orion & Lepus',                                                                                                  '8'),
('1753jf13',    'Monoceros, Canis Major & Minor, Navis, Lepus',                                                                             '8'),
('1753jf14',    'Hydra, Crater, Corvus, Sextans, Virgo',                                                                                    '8'),
('1753jf15',    'Cassiopea, Cepheus, Ursa Minor, Draco',                                                                                    '8'),
('1753jf16',    'Andromeda, Perseus, Triangulum',                                                                                           '8'),
('1753jf17',    'Camelopardal & Auriga',                                                                                                    '8'),
('1753jf18',    'Lynx & Leo Minor',                                                                                                         '8'),
('1753jf19',    'Ursa Major',                                                                                                               '8'),
('1753jf20',    'Comae Berenices, Bootes, Canes Venatici',                                                                                  '8'),
('1753jf21',    'Hercules, Corona & Lyra',                                                                                                  '8'),
('1753jf22',    'Ophiuchus & Serpens',                                                                                                      '8'),
('1753jf23',    'Aquila, Sagitta, Vulpecula &amp; Anser, Delphinus',                                                                        '8'),
('1753jf24',    'Lyra, Cygnus, Lacerta, Vulpec & Anser, Sagitta',                                                                           '8'),
('1753jf25',    'Pegasus, Equuleus',                                                                                                        '8'),
('1753jf26',    'Northern Hemisphere',                                                                                                      '8'),
('1753jf26b',   'Northern Hemisphere (Recolored)',                                                                                          '8'),
('1753jf27',    'Southern Hemisphere',                                                                                                      '8'),
('1776jnf01',   'Hémisphere Boréal',                                                                                                        '9'),
('1776jnf02',   'Cassiopée, Céphée, Renne, Petite Ourse, Dragon',                                                                           '9'),
('1776jnf03',   'Andromède, Persée, Triangle',                                                                                              '9'),
('1776jnf04',   'Girafe, Cocher',                                                                                                           '9'),
('1776jnf05',   'Lynx, Petit Lion',                                                                                                         '9'),
('1776jnf06',   'Grande Ourse',                                                                                                             '9'),
('1776jnf07',   'Bouvier, les Lévriers, Chevelure de Berenice',                                                                             '9'),
('1776jnf08',   'Hercule, Couronne',                                                                                                        '9'),
('1776jnf09',   'Serpentaire & Serpent',                                                                                                    '9'),
('1776jnf10',   'Aigle, Antinous, Flèche, Renard, Dauphin',                                                                                 '9'),
('1776jnf11',   'Lyre, Cygne, Lézard, Renard',                                                                                              '9'),
('1776jnf12',   'Pegase, Petit Cheval, Dauphin',                                                                                            '9'),
('1776jnf13',   'Bélier',                                                                                                                   '9'),
('1776jnf14',   'Taureau',                                                                                                                  '9'),
('1776jnf15',   'Gémeaux',                                                                                                                  '9'),
('1776jnf16',   'Cancer',                                                                                                                   '9'),
('1776jnf17',   'Lion',                                                                                                                     '9'),
('1776jnf18',   'Vierge',                                                                                                                   '9'),
('1776jnf19',   'Balance & Scorpion',                                                                                                       '9'),
('1776jnf20',   'Sagittaire',                                                                                                               '9'),
('1776jnf21',   'Capricorne & Verseau',                                                                                                     '9'),
('1776jnf22',   'Poissons',                                                                                                                 '9'),
('1776jnf23',   'Baleine',                                                                                                                  '9'),
('1776jnf24',   'Eridan, Orion & Lièvre',                                                                                                   '9'),
('1776jnf25',   'Licorne, Grand Chien',                                                                                                     '9'),
('1776jnf26',   'Hydre, Sextant',                                                                                                           '9'),
('1776jnf27',   'Hydre, Coupe, Corbeau',                                                                                                    '9'),
('1776jnf28',   'Hémisphere Austral',                                                                                                       '9'),
('1776jnf29',   'Planisphere des Etoiles Australes',                                                                                        '9'),
('1805jeb02',   'Kleine Bar, Drache, Cepheus, Cassiopeia',                                                                                  '10'),
('1805jeb03',   'Perseus, Andromeda, die Triangel',                                                                                         '10'),
('1805jeb04',   'Cameelopard, Fuhrmann',                                                                                                    '10'),
('1805jeb05',   'Linx, Kleine Lowe',                                                                                                        '10'),
('1805jeb06',   'Der Grosse Bar',                                                                                                           '10'),
('1805jeb07',   'Bootes, die Jagdhunde, Haupthaar der Berenice',                                                                            '10'),
('1805jeb08',   'Herkules, Nordliche Krone',                                                                                                '10'),
('1805jeb09',   'Ophiuchus, Schlange',                                                                                                      '10'),
('1805jeb10',   'Adler, Antinous, Pfeil, Fuchs & Gans, Delphin',                                                                            '10'),
('1805jeb11',   'Leyer, Schwan, Eidexe',                                                                                                    '10'),
('1805jeb12',   'Pegasus, Fullen',                                                                                                          '10'),
('1805jeb13',   'Widder',                                                                                                                   '10'),
('1805jeb14',   'Stier',                                                                                                                    '10'),
('1805jeb15',   'Die Zwillinge',                                                                                                            '10'),
('1805jeb16',   'Krebs',                                                                                                                    '10'),
('1805jeb17',   'Lowe',                                                                                                                     '10'),
('1805jeb18',   'Jungfrau',                                                                                                                 '10'),
('1805jeb19',   'Waage, Scorpion',                                                                                                          '10'),
('1805jeb20',   'Schutze',                                                                                                                  '10'),
('1805jeb21',   'Steinbock, Wassermann, der Sudliche Fisch',                                                                                '10'),
('1805jeb22',   'Die Fische',                                                                                                               '10'),
('1805jeb23',   'Wallfisch',                                                                                                                '10'),
('1805jeb24',   'Eridanus Fluss, Orion, Haase, Taube',                                                                                      '10'),
('1805jeb25',   'Einhorn, Grosse & Kleine Hund, Schiff',                                                                                    '10'),
('1805jeb26',   'Wasserschlange, Sextant',                                                                                                  '10'),
('1805jeb27',   'Wasserschlange, Becher, Rabe',                                                                                             '10'),
('1822aj00',    'Charts of Zodiacal Signs',                                                                                                 '11'),
('1822aj01',    'Northern Celestial Hemisphere',                                                                                            '11'),
('1822aj02',    'Ursa Minor, Cassiopeia, Tarandus, Cepheus, Draco, Custos Messium',                                                         '11'),
('1822aj03',    'Andromeda, Perseus & Caput Medusae, Triangula & Gloire de Frederic',                                                       '11'),
('1822aj04',    'Auriga, Camelopardalis & Telescopium Herschelii',                                                                          '11'),
('1822aj05',    'Lynx & Leo Minor',                                                                                                         '11'),
('1822aj06',    'Ursa Major',                                                                                                               '11'),
('1822aj07',    'Bootes & Mons Maenalus, Asterion & Chara or Canes Venatici, Coma Berenices & Quadraus Muralis',                            '11'),
('1822aj08',    'Corona Borealis, Hercules & Cerberus, Lyra',                                                                               '11'),
('1822aj09',    'Ophiuchus or Serpentarius & Serpens',                                                                                      '11'),
('1822aj10',    'Aquila & Antinous, Scutum Sobieski, Taurus Poniatowski, Sagitta, Vulpecula & Anser, Delphinus',                            '11'),
('1822aj11',    'Cygnus, Lacerta & Lyra',                                                                                                   '11'),
('1822aj12',    'Pegasus & Equuleus',                                                                                                       '11'),
('1822aj13',    'Aries',                                                                                                                    '11'),
('1822aj14',    'Taurus',                                                                                                                   '11'),
('1822aj15',    'Gemini',                                                                                                                   '11'),
('1822aj16',    'Cancer',                                                                                                                   '11'),
('1822aj17',    'Leo',                                                                                                                      '11'),
('1822aj18',    'Virgo',                                                                                                                    '11'),
('1822aj19',    'Libra & Scorpio',                                                                                                          '11'),
('1822aj20',    'Sagittarius & Corona Australis',                                                                                           '11'),
('1822aj21',    'Aquarius, Capricornus & Piscis Australis',                                                                                 '11'),
('1822aj22',    'Pisces',                                                                                                                   '11'),
('1822aj23',    'Cetus, Apparatus Sculptoris, Machina Electrica & Officina Chemica',                                                        '11'),
('1822aj24',    'Fluvius Eridanus, Orion, Lepus, Columba, Cela Sculptoris, Fornax Chemica, Psalterium Georgii & Brandenburgium Sceptrum',   '11'),
('1822aj25',    'Monoceros, Canis Major & Minor, Orion, Columba Noachi, Argo Navis & Pyxis Nautica',                                        '11'),
('1822aj26',    'Hydra, Sextans, Crater, Felis, Antlia Pneumatica, Pyxis Nautica & Argo Navis',                                             '11'),
('1822aj27',    'Hydra, Corvus, Noctua, Centaurus, Lupus & Crater',                                                                         '11'),
('1822aj28',    'Southern Celestial Hemisphere',                                                                                            '11'),
('1822aj29',    'Principal Stars Visible to Great Britain',                                                                                 '11'),
('1822aj30',    'The Moon, Venus, Jupiter & Saturn',                                                                                        '11'),
('1824jg01',    'Constellations near Via Lactea',                                                                                           '12'),
('1824jg02',    'Constellations near Ursa Major',                                                                                           '12'),
('1824jg03',    'Constellations near the Lynx',                                                                                             '12'),
('1824jg04',    'Constellations near Perseus',                                                                                              '12'),
('1824jg05',    'Constellations near Cygnus',                                                                                               '12'),
('1824jg06',    'Constellations near Corona Borealis',                                                                                      '12'),
('1824jg07',    'Constellations near Ophiuchus & Serpens',                                                                                  '12'),
('1824jg08',    'Constellations near Delphinus',                                                                                            '12'),
('1824jg09',    'Constellations near Pisces',                                                                                               '12'),
('1824jg10',    'Constellations near Taurus',                                                                                               '12'),
('1824jg11',    'Constellations near Cancer',                                                                                               '12'),
('1824jg12',    'Constellations near Virgo',                                                                                                '12'),
('1824jg13',    'Constellations near Scorpio',                                                                                              '12'),
('1824jg14',    'Constellations near Capricornus',                                                                                          '12'),
('1824jg15',    'Constellations near Cetus',                                                                                                '12'),
('1824jg16',    'Constellations near Canis Major',                                                                                          '12'),
('1824jg17',    'Constellations near Hydra',                                                                                                '12'),
('1824jg18',    'Principal Stars in the Northern Hemisphere',                                                                               '12'),
('1824jg19',    'Telescopic Appearance of the Moon',                                                                                        '12'),
('1824rrb01',   'Draco & Ursa Minor',                                                                                                       '13'),
('1824rrb02',   'Camelopardalis, Tarandus & Custos Messium',                                                                                '13'),
('1824rrb03',   'Cassiopeia',                                                                                                               '13'),
('1824rrb04',   'Cepheus',                                                                                                                  '13'),
('1824rrb05',   'Gloria Frederici, Andromeda & Triangula',                                                                                  '13'),
('1824rrb06',   'Perseus & Caput Medusae',                                                                                                  '13'),
('1824rrb07',   'Auriga',                                                                                                                   '13'),
('1824rrb08',   'Lynx & Telescopium Herschilii',                                                                                            '13'),
('1824rrb09',   'Ursa Major',                                                                                                               '13'),
('1824rrb10',   'Bootes, Canes Venatici, Coma Berenices & Quadrans Muralis',                                                                '13'),
('1824rrb11',   'Hercules & Corona Borealis',                                                                                               '13'),
('1824rrb12',   'Taurus Poniatowski, Serpentarius, Scutum Sobiesky & Serpens',                                                              '13'),
('1824rrb13',   'Delphinus, Sagitta, Aquila & Antinous',                                                                                    '13'),
('1824rrb14',   'Lacerta, Cygnus, Lyra, Vulpecula &amp; Anser',                                                                             '13'),
('1824rrb15',   'Pegasus & Equuleus',                                                                                                       '13'),
('1824rrb16',   'Aries & Musca Borealis',                                                                                                   '13'),
('1824rrb17',   'Taurus',                                                                                                                   '13'),
('1824rrb18',   'Gemini',                                                                                                                   '13'),
('1824rrb19',   'Cancer',                                                                                                                   '13'),
('1824rrb20',   'Leo Major & Leo Minor',                                                                                                    '13'),
('1824rrb21',   'Virgo',                                                                                                                    '13'),
('1824rrb22',   'Libra',                                                                                                                    '13'),
('1824rrb23',   'Scorpio',                                                                                                                  '13'),
('1824rrb24',   'Sagittarius & Corona Australis, Microscopium & Telescopium',                                                               '13'),
('1824rrb25',   'Capricornus',                                                                                                              '13'),
('1824rrb26',   'Aquarius, Piscis Australis & Ballon Aerostatique',                                                                         '13'),
('1824rrb27',   'Pisces',                                                                                                                   '13'),
('1824rrb28',   'Psalterium Georgii, Fluvius Eridanus, Cetus, Officina Sculptoris, Fornax Chemica & Machine Electrica',                     '13'),
('1824rrb29',   'Orion',                                                                                                                    '13'),
('1824rrb30',   'Canis Major, Lepus, Columba Noachi & Cela Sculptoris',                                                                     '13'),
('1824rrb31',   'Monoceros, Canis Minor & Atelier Typographique',                                                                           '13'),
('1824rrb32',   'Noctua, Corvus, Crater, Sextans Uranie, Hydra, Felis, Lupus, Centaurus, Antlia Pneumatica, Argo Navis & Pyxis Nautica',    '13'),
('1835ehb1',    'A Plan of the Solar System Exhibiting its Relative Magnitudes & Distances',                                                '14'),
('1835ehb2',    'The Constellations in October, November, December',                                                                        '14'),
('1835ehb3',    'The Constellations in January, February, March',                                                                           '14'),
('1835ehb4',    'The Constellations in April, May, June',                                                                                   '14'),
('1835ehb5',    'The Constellations in July, August, September',                                                                            '14'),
('1835ehb6',    'Northern Circumpolar Map for each Month of the Year',                                                                      '14'),
('1835ehb7',    'Southern Circumpolar Map for each Month of the Year',                                                                      '14'),
('1835ehb8',    'A Celestial Planisphere, or Map of the Heavens',                                                                           '14'),
('1844wrd1',    'N°1',                                                                                                                      '15'),
('1844wrd2',    'N°2',                                                                                                                      '15'),
('1844wrd3',    'N°3',                                                                                                                      '15'),
('1844wrd4',    'N°4',                                                                                                                      '15'),
('1844wrd5',    'Circumjacent the North Pole',                                                                                              '15'),
('1844wrd6',    'Circumjacent the South Pole',                                                                                              '15'),
('1850as01',    'Largest Telescopes',                                                                                                       '16'),
('1850as02',    'Orrery',                                                                                                                   '16'),
('1850as03',    'Solar System',                                                                                                             '16'),
('1850as04',    'Forces, Circles, Kepler Law & Place of Earth',                                                                             '16'),
('1850as05',    'Sun & Spots on the Sun, Transits of Mercury & Venus',                                                                      '16'),
('1850as06',    'Signs of the Zodiac',                                                                                                      '16'),
('1850as07',    'Mercury & Venus',                                                                                                          '16'),
('1850as08',    'Definitions',                                                                                                              '16'),
('1850as09',    'The Seasons',                                                                                                              '16'),
('1850as10',    'Mars & Jupiter',                                                                                                           '16'),
('1850as11',    'Saturn',                                                                                                                   '16'),
('1850as12',    'Herschel or Uranus & Leverrier or Neptune',                                                                                '16'),
('1850as13',    'Phases of the Moon',                                                                                                       '16'),
('1850as14',    'Telescopic View of the New Moon',                                                                                          '16'),
('1850as15',    'Telescopic View of the Full Moon',                                                                                         '16'),
('1850as16',    'Telescopic View of the Moon',                                                                                              '16'),
('1850as17',    'Eclipses',                                                                                                                 '16'),
('1850as18',    'Moons Nodes & Eclipses',                                                                                                   '16'),
('1850as19',    'Greatest Number of Eclipses in One Year',                                                                                  '16'),
('1850as20',    'Tides',                                                                                                                    '16'),
('1850as21',    'Orbits of the Planets',                                                                                                    '16'),
('1850as22',    'Refraction, Parallax, Light & Heat',                                                                                       '16'),
('1850as23',    'Terrestrial & Celestial Globes',                                                                                           '16'),
('1850as24',    'Binary or Double Stars',                                                                                                   '16'),
('1850as25',    'Nebulae or Clusters of Stars',                                                                                             '16'),
('1850as26',    'Visible Heavens from January 21st to April 17th',                                                                          '16'),
('1850as27',    'Visible Heavens from April 18th to July 21st',                                                                             '16'),
('1850as28',    'Visible Heavens from July 22nd to October 31st',                                                                           '16'),
('1850as29',    'Visible Heavens from November 1st to January 20th',                                                                        '16'),
('1855lp01',    'Die Central Sonne',                                                                                                        '17'),
('1855lp02',    'Himmels Karte',                                                                                                            '17'),
('1855lp03',    'Darstellung des Sonnensystems',                                                                                            '17'),
('1855lp04',    'Vergleichende Darstellung der Grösse der Planeten',                                                                        '17'),
('1855lp05',    'Die Sonne',                                                                                                                '17'),
('1855lp06',    'Der Mond',                                                                                                                 '17'),
('1855lp07',    'Transparente Darstellung der Mondsphasen',                                                                                 '17'),
('1855lp08',    'Finsternisse',                                                                                                             '17'),
('1855lp09',    'Ansicht von den Jahreszeiten',                                                                                             '17'),
('1855lp10',    'Die Erde & ihre Atmosphäre',                                                                                               '17'),
('1855lp11',    'Kometen & Aerolithen',                                                                                                     '17'),
('1855lp12',    'Meteorologie',                                                                                                             '17'),
('1865sduk1',   'N°1',                                                                                                                      '18'),
('1865sduk2',   'N°2',                                                                                                                      '18'),
('1865sduk3',   'N°3',                                                                                                                      '18'),
('1865sduk4',   'N°4',                                                                                                                      '18'),
('1865sduk5',   'Circumjacent the North Pole',                                                                                              '18'),
('1865sduk6',   'Circumjacent the South Pole',                                                                                              '18'),
('1869akj01',   'Earth - Sun - Moon Relationships',                                                                                         '19'),
('1869akj02',   'Day & Night',                                                                                                              '19'),
('1869akj03',   'Sun',                                                                                                                      '19'),
('1869akj04',   'Moon',                                                                                                                     '19'),
('1869akj05',   'Eclipse of the Sun',                                                                                                       '19'),
('1869akj06',   'Eclipse of the Moon',                                                                                                      '19'),
('1869akj07',   'The Solar System',                                                                                                         '19'),
('1869akj08',   'Position of the Earth in the Solar System',                                                                                '19'),
('1869akj09',   'Planet Relationships',                                                                                                     '19'),
('1869akj10',   'Comets',                                                                                                                   '19'),
('1869akj11',   'Star Relationships',                                                                                                       '19'),
('1869akj12',   'Nebulae',                                                                                                                  '19'),
('1869akj13',   'Meteors',                                                                                                                  '19'),
('1869akj14',   'Spectrum Analysis Applied to the Sun & Stars',                                                                             '19'),
('1869akj15',   'Maps of the Stars N°1',                                                                                                    '19'),
('1869akj16',   'Maps of the Stars N°2',                                                                                                    '19'),
('1869akj17',   'Maps of the Stars N°3',                                                                                                    '19'),
('1869akj18',   'Maps of the Stars N°4',                                                                                                    '19'),
('1869akj19',   'Maps of the Stars N°5 - The North Pole',                                                                                   '19'),
('1869akj20',   'Maps of the Stars N°6 - The South Pole',                                                                                   '19'),
('1869akj21',   'Ecliptic Charts Illustrating the Apparent Paths of the Planets Venus, Mars, Jupiter & Saturn in 1868-9',                   '19');
